---
- name: Install SDKMAN
  shell: curl -s "https://get.sdkman.io" | bash

- name: Complete installation SDKMAN
  shell: source "$HOME/.sdkman/bin/sdkman-init.sh"

- name: Deploy sdkman.sh
  template:
    src: 06_sdkman.sh
    dest: ~/.zsh.d/06_sdkman.sh
    mode: 0755
