---
- name: Set nodebrew path
  template:
    src: 001_nodebrew.sh
    dest: ~/.bash.d/001_nodebrew.sh
    mode: 0755

- name: Set nodebrew path
  template:
    src: 001_nodebrew.sh
    dest: ~/.zsh.d/001_nodebrew.sh
    mode: 0755

- name: Check installed node.js
  shell: $SHELL -lc "which node"
  register: nodejs_installed
  failed_when: nodejs_installed.rc != 1 and nodejs_installed.rc != 0
  
- name: Check installed node.js version
  shell: $SHELL -lc "nodebrew ls | grep {{ nodebrew_nodejs_version }}"
  when: nodejs_installed.rc == 0
  register: nodejs_target_version_exist

- name: Check nodebrew dir exists
  stat:
    path: "$HOME/.nodebrew/src"
  register: nb_directory_created

- name: Mkdir nodebrew dir
  file: 
    path: "$HOME/.nodebrew/src"
    state: directory
    mode: 0755
  when: not nb_directory_created.stat.exists
  
- name: Install node.js
  shell: $SHELL -lc "nodebrew install-binary {{ nodebrew_nodejs_version }}"
  when: (nodejs_installed.rc == 1) or (nodejs_target_version_exist.rc == 1)

- name: Select node.js version
  shell: $SHELL -lc "nodebrew use {{ nodebrew_nodejs_version }}"

- name: Update npm
  shell: $SHELL -lc "npm update -g npm"
  when: nodebrew_npm_update
