---
- name: Mkdir .ssh
  file:
    path: ~/.ssh
    state: directory
    mode: 0755

- name: Generate key pair for github
  openssh_keypair: 
    path: "$HOME/.ssh/id_rsa"

- name: Generate key pair for gitlab
  openssh_keypair: 
    path: "$HOME/.ssh/gitlab_rsa"

- name: Set config file
  template:
    src: config
    dest: ~/.ssh/config
    mode: 0644
