---
- name: Mkdir .ssh
  file:
    path: ~/.ssh
    state: directory
    mode: 0755

- name: Generate key pair for github
  openssh_keypair:
    path: "$HOME/.ssh/id_rsa"

- name: Generate key pair for gitlab
  openssh_keypair:
    path: "$HOME/.ssh/gitlab_rsa"

- name: Check file ~/.ssh/config
  stat:
    path: ~/.ssh/config
  register: exists_config

- name: Set config file
  template:
    src: config
    dest: ~/.ssh/config
    mode: 0644
  when: not exists_config.stat.exists