---
- name: deploy shell
  template:
    src: shells
    dest: /etc/shells
    mode: 0755
  become: yes

- name: change login shell
  command: chsh -s /usr/local/bin/zsh
  become: yes

- name: install prezto
  git:
    repo: https://github.com/sorin-ionescu/prezto.git
    dest: "${HOME}/.zprezto"

- name: configure prezto
  command: |
    /usr/local/bin/zsh -lc "setopt EXTENDED_GLOB
    for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
      ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
    done"
  ignore_errors: True

- name: deploy .zshrc
  template:
    src: .zshrc
    dest: ~/.zshrc
    mode: 0644

- name: remove ~/.zcompdump
  file:
    path: ~/.zcompdump
    state: absent

