---
- name: deploy shell
  template:
    src: shells
    dest: /etc/shells
    mode: 0755
  become: yes

- name: change login shell
  command: chsh -s /usr/local/bin/zsh
  become: yes

- name: check prezto already exists
  stat:
    path: "${HOME}/.zprezto"
  register: prezto_exists

- name: Install prezto
  git:
    repo: https://github.com/sorin-ionescu/prezto.git
    dest: "${HOME}/.zprezto"
  when: not prezto_exists.stat.exists

- name: Configure prezto
  command: |
    /usr/local/bin/zsh -lc "setopt EXTENDED_GLOB
    for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
      ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
    done"
  ignore_errors: True

- name: Deploy .zshrc
  template:
    src: .zshrc
    dest: ~/.zshrc
    mode: 0644

- name: Change nano to vim
  template:
    src: .zprofile
    dest: ~/.zprofile
    mode: 0644

- name: Remove ~/.zcompdump
  file:
    path: ~/.zcompdump
    state: absent
