---
- name: Homebrew tap
  homebrew_tap:
    name: "{{ item }}"
    state: "present"
  with_items: "{{ brew_taps }}"

- name: Install Homebrew Cask Packages
  homebrew_cask:
    name: "{{ item }}"
    state: "present"
    install_options: "appdir=/Applications"
    accept_external_apps: yes
  with_items: "{{ brew_cask_apps }}"

- name: Update Homebrew
  homebrew:
    update_homebrew: yes

- name: Install Homebrew Packages
  homebrew:
    name: "{{ brew_packages }}"
    state: "present"

- name: Check Oh My Zsh dir
  stat:
    path: "{{ansible_env.HOME}}/.oh-my-zsh"
  register: already_initialize_oh_my_zsh

- name: Install Oh My Zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: not already_initialize_oh_my_zsh.stat.exists

- name: Mkdir .zsh.d
  file:
    path: ~/.zsh.d
    state: directory
    mode: 0755

- name: Deploy thefuck.sh
  template:
    src: 02_thefuck.sh
    dest: ~/.zsh.d/02_thefuck.sh
    mode: 0755

- name: set zshrc
  tags: zsh
  template:
    src: .zshrc
    dest: ~/.zshrc
    mode: 0644
  when: not exists_zshrc.stat.exists

- name: Initialize anyenv
  shell: anyenv init
  ignore_errors: true

- name: Check file
  stat:
    path: "{{ansible_env.HOME}}/.config/anyenv/anyenv-install"
  register: already_initialize_anyenv

- name: Initialize anyenv install
  shell: yes | anyenv install --init
  when: not already_initialize_anyenv.stat.exists
