---
- name: Set git alias status
  shell: git config --global alias.{{ item.alias }} "{{ item.cmd }}"
  with_items:
    - { alias: 'st', cmd: 'status' }
    - { alias: 'c', cmd: 'checkout' }
    - { alias: 'b', cmd: 'branch' }

- name: Set git settings
  shell: |
    git config --global push.default current
    git config --global pull.ff only
    git config --global pull.rebase false
    git config --global user.name {{ git_user }}
    git config --global user.email {{ git_email }}
