---
brew_taps:
  - homebrew/core
  - caskroom/cask
  - go-swagger/go-swagger
brew_cask_apps:
  - alfred
  - docker
  - firefox
  - google-chrome
  - google-japanese-ime
  - iterm2
  - visual-studio-code
  - evernote
  - slack
  - shiftit
  - wechat
  - coteditor
  - jetbrains-toolbox
  - insomnia
brew_packages:
  - autoconf
  - awscli
  - bash-completion
  - docker-compose
  - docker-machine
  - git
  - jq
  - nmap
  - openssl
  - tig
  - tree
  - wget
  - zsh
  - zsh-syntax-highlighting
  - nodebrew
  - rbenv
  - ruby-build
  - go
  - protobuf
  - thefuck
  - coreutils
  - findutils
  - gnu-tar
  - gnu-sed
  - gawk
  - gnutls
  - gnu-indent
  - gnu-getopt
  - grep
  - go-swagger
  - zsh-completions
  - zsh-autosuggestions
git_user: izumix03
git_email: takahiro.izumikawa@gmail.com
