---
brew_taps:
  - homebrew/core
  - homebrew/cask
brew_cask_apps:
  - alfred
  - docker
  - google-chrome
  - google-japanese-ime
  - iterm2
  - visual-studio-code
  - evernote
  - slack
  - shiftit
  - coteditor
  - jetbrains-toolbox
  - insomnia
  - kindle
brew_packages:
  - autoconf
  - awscli
  - jq
  - nmap
  - openssl
  - tig
  - tree
  - wget
  - anyenv
  - thefuck
  - peco
git_user: izumix03
git_email: takahiro.izumikawa@gmail.com
