---
- name: Homebrew tap
  homebrew_tap:
    name: "{{ item }}"
    state: "present"
  with_items: "{{ brew_taps }}"

- name: Install Homebrew Cask Packages
  homebrew_cask:
    name: "{{ item }}"
    state: "present"
    install_options: "appdir=/Applications"
    accept_external_apps: yes
  with_items: "{{ brew_cask_apps }}"

- name: Update Homebrew
  homebrew:
    update_homebrew: yes

- name: Install Homebrew Packages
  homebrew:
    name: "{{ brew_packages }}"
    state: "present"

- name: Mkdir .zsh.d
  file:
    path: ~/.zsh.d
    state: directory
    mode: 0755

- name: Deploy 001_thefuck.sh
  template:
    src: 001_thefuck.sh
    dest: ~/.zsh.d/001_thefuck.sh
    mode: 0755

- name: Deploy 002_anyenv.sh
  template:
    src: 002_anyenv.sh
    dest: ~/.zsh.d/002_anyenv.sh
    mode: 0755

- name: Initial config for git (user)
  shell: git config --global user.name {{ git_user }}

- name: Initial config for git (email)
  shell: git config --global user.email {{ git_email }}

- name: Change git push default
  shell: git config push.default current

- name: set zshrc
  tags: zsh
  template:
    src: .zshrc
    dest: ~/.zshrc
    mode: 0644

- name: Initialize anyenv
  shell: anyenv init && anyenv install --init
