---
- name: Homebrew tap
  homebrew_tap:
    name: "{{ item }}"
    state: "present"
  with_items: "{{ brew_taps }}"

- name: Install Homebrew Cask Packages
  homebrew_cask:
    name: "{{ item }}"
    state: "present"
    install_options: "appdir=/Applications"
    accept_external_apps: yes
  with_items: "{{ brew_cask_apps }}"

- name: Update Homebrew
  homebrew:
    update_homebrew: yes

- name: Install Homebrew Packages
  homebrew:
    name: "{{ brew_packages }}"
    state: "present"

- name: deploy .bash_profile
  template:
    src: .bash_profile
    dest: ~/.bash_profile
    mode: 0644

- name: mkdir .bash.d
  file:
    path: ~/.bash.d
    state: directory
    mode: 0755
